<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>BetterUI.Unity6InteropFixer</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dnlib" Version="4.5.0" />
  </ItemGroup>
</Project>
