<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>10.0</LangVersion>
    <AssemblyName>InfernoProtocol.BetterLights</AssemblyName>
    <RootNamespace>InfernoProtocol.BetterLights</RootNamespace>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <Version>0.3.1</Version>
    <FileVersion>0.3.1.0</FileVersion>
    <AssemblyVersion>0.3.1.0</AssemblyVersion>
    <Deterministic>true</Deterministic>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <DebugType>portable</DebugType>
    <GameDir Condition="'$(GameDir)' == ''">C:\Program Files (x86)\Steam\steamapps\common\Inferno Protocol</GameDir>
    <BepInExCore>$(GameDir)\BepInEx\core</BepInExCore>
    <InteropDir>$(GameDir)\BepInEx\interop</InteropDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx.Core" HintPath="$(BepInExCore)\BepInEx.Core.dll" Private="false" />
    <Reference Include="BepInEx.Unity.IL2CPP" HintPath="$(BepInExCore)\BepInEx.Unity.IL2CPP.dll" Private="false" />
    <Reference Include="Il2CppInterop.Runtime" HintPath="$(BepInExCore)\Il2CppInterop.Runtime.dll" Private="false" />
    <Reference Include="Assembly-CSharp" HintPath="$(InteropDir)\Assembly-CSharp.dll" Private="false" />
    <Reference Include="Il2Cppmscorlib" HintPath="$(InteropDir)\Il2Cppmscorlib.dll" Private="false" />
    <Reference Include="Il2CppSystem" HintPath="$(InteropDir)\Il2CppSystem.dll" Private="false" />
    <Reference Include="UnityEngine.CoreModule" HintPath="$(InteropDir)\UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="Unity.InputSystem" HintPath="$(InteropDir)\Unity.InputSystem.dll" Private="false" />
    <Reference Include="Unity.Netcode.Runtime" HintPath="$(InteropDir)\Unity.Netcode.Runtime.dll" Private="false" />
    <Reference Include="UnityEngine.ParticleSystemModule" HintPath="$(InteropDir)\UnityEngine.ParticleSystemModule.dll" Private="false" />
    <Reference Include="UnityEngine.TextRenderingModule" HintPath="$(InteropDir)\UnityEngine.TextRenderingModule.dll" Private="false" />
    <Reference Include="UnityEngine.UI" HintPath="$(InteropDir)\UnityEngine.UI.dll" Private="false" />
    <Reference Include="UnityEngine.UIModule" HintPath="$(InteropDir)\UnityEngine.UIModule.dll" Private="false" />
    <Reference Include="Unity.TextMeshPro" HintPath="$(InteropDir)\Unity.TextMeshPro.dll" Private="false" />
  </ItemGroup>
</Project>
